//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokExamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Musteri()
        {
            this.tbl_GirisCikis = new HashSet<tbl_GirisCikis>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public Nullable<decimal> telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GirisCikis> tbl_GirisCikis { get; set; }
    }
}
