//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokExamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GirisCikis
    {
        public int id { get; set; }
        public int urun_id { get; set; }
        public int musteri_id { get; set; }
        public System.DateTime ıslemZamani { get; set; }
        public string hareket { get; set; }
        public int miktar { get; set; }
    
        public virtual tbl_Musteri tbl_Musteri { get; set; }
        public virtual tbl_Urun tbl_Urun { get; set; }
    }
}
